<<<<<<< HEAD
info:
  component: Config Samples
endpoints:
  restart:
    enabled: true
logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG
=======
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/spring-cloud-samples/config-repo
#          uri: https://github.com/hub830/config-repo
          uri: http://192.168.254.247:3000/fox/config-repo-{application}
#          searchPaths: '{application}/{profile}/{label}'
#          searchPaths: '{label}'
          basedir: target/config

>>>>>>> 33675dab28e6aa741203449133e29ffc22737771
